name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

      - name: Pack NuGet
        run: dotnet pack

      - name: Publish NuGet
        run: dotnet nuget push src/bin/Release/matkoch.project-defaults.${{ env.fullSemVer }}.nupkg --source nuget --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Add Tag
        run: |
          git tag ${{ env.fullSemVer }}
          git push origin ${{ env.fullSemVer }}
